name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger deployment on pushes to master (or main)
    paths:
      - '**/*'  # Trigger the workflow whenever any file is modified or added

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Build the website (Optional step for frameworks)
        run: |
          # If you are using a static site generator or build tool, run the build command here
          # e.g., npm run build or yarn build
          echo "Building website..."

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch to deploy to (usually 'gh-pages')
          folder: ./  # The folder containing the files to deploy (set to './' for root)
          token: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides a token for actions

